[package]
name = "nx-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer", version = "0.1.0" }
parser = { path = "../parser", version = "0.1.0" }
evaluator = { path = "../evaluator", version = "0.1.0" }
